spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/AplicacaoSpring?useTimezone=true&serverTimezone=UTC
    username: suporte
    password: Pedro1001@
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: false
